### ISSUE TITLE
Image Recognition

### ISSUE THREAD

**Issue by lapost48** [RowanASRCResearch/Image-Fusion#1]
Client desires the capability to differentiate objects from each other in the software. The software should be able to determine whether highlighted pixels are a person, vehicle, or building.

**Comment by Willowlark** [comment]
People can now be recognized.

**Comment by Willowlark** [comment]
Can possibly use either 
- http://cloudsightapi.com/api
- https://www.clarifai.com/demo
  to add better IR

**Comment by Willowlark** [comment]
Looks like we're pretty much done on new features, so what we have in the recognition module will be the extent of the work.
